# Generated by Django 4.0.5 on 2022-06-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_photo_created_at_alter_photo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
    ]
