# Generated by Django 4.0.5 on 2022-06-07 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_created_at_alter_album_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
    ]
